### ISSUE TITLE
this tool's name conflicts with an older, similar Go tool

### ISSUE THREAD

**Issue by mvdan** [go-tooling/modcons#5]
This name has been used by @rogpeppe for almost two months: https://github.com/rogpeppe/modcop

I know we didn't directly copy the name from any other Go project, because we discussed a bunch of names along with @myitcv.

Perhaps you came up with this name on your own as well, but for the sake of avoiding confusion, I'd ask that you rename the project. The two tools are for Go modules, so there's a high chance that yours would bring confusion to existing users of Roger's tool.

Thanks!

**Comment by myles-mcdonnell** [comment]
Thanks for bringing this to my attention, yes just an unfortunate clash.  No problem, I'll go ahead and rename it.  

1) what process should I/we  follow to find a new name? 
2) I'm think to implement the new name I'll leave this repo in place but with rename details on the readme..I can then direct reads to https://github.com/rogpeppe/modcop and https://github.com/go-tooling/{new_name}

howzat?

**Comment by mvdan** [comment]
Thanks for the response!

I don't know about new names - we just threw around random names until we found one we liked :)

Also, GitHub handles renames properly, so even if you rename this to github.com/go-tooling/modfoo, the modcop url will still redirect to that new repository. I don't think setting up a separate repository to point to the other two repos would be necessary.

**Comment by myles-mcdonnell** [comment]
@mvdan cool, good to know GH takes care of the redirect from old name..so unless there is any reason not to I'm going with _modcons_ (module constraints) for the new name.

**Comment by mvdan** [comment]
Sounds good! The issue can be closed :)
